### ISSUE TITLE
z.record(z.null()) results in invalid OpenAPI schema

### ISSUE THREAD

**Issue by MattIPv4** [asteasolutions/zod-to-openapi#139]
Using `z.record(z.null())` in a schema results in the following being generated in the OpenAPI schema, which fails OpenAPI schema validation:

```yaml
additionalProperties:
  - type: "null"
  - nullable: true
```

I believe this should just generate:

```yaml
additionalProperties:
  - nullable: true
```
