### ISSUE TITLE
`catchall` does not generate `additionalProperties`

### ISSUE THREAD

**Issue by MattIPv4** [asteasolutions/zod-to-openapi#154]
When using `catchall` on a ZodObject, I would expect the resulting OpenAPI schema to contain `additionalProperties` based on what the `catchall` specifies.

For example, with `z.object({}).catchall(z.union([ z.boolean(), z.number(), z.string() ]))` I would expect:

```yaml
additionalProperties:
  anyOf:
    - type: boolean
    - type: number
    - type: string
```

https://runkit.com/mattipv4/649f42bb14551b0008a9ca8f
