### ISSUE TITLE
Add a tag to a schema

### ISSUE THREAD

**Issue by damianobarbati** [asteasolutions/zod-to-openapi#216]
In order to use the `x-tagGroups` of redoc, I need to provide a tag to every operation and schema I want to list in the sidebar.

All good with operations, but how can I provide a tag when I use the `.openapi('UserSchema')`?

**Comment by AGalabov** [comment]
Hello @damianobarbati thank you for using our library. Would you be able to provide an example of a schema in the OpenAPI specification of what you are trying to achieve

**Comment by damianobarbati** [comment]
@AGalabov sure, here an example:
```yml
servers:
  - url: https://api-cesc.cryopdp.com/
x-tagGroups:
  - name: API reference
    tags:
      - Auth
      - User
      - Shipment
      - Password reset
      - API Key
  - name: Schemas
    tags:
      - metric
      - last_metric
      - user
      - shipment
components:
  schemas:
    metric:
      type: object
      properties:
        id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
....
        is_out_of_threshold:
          type: boolean
      required:
        - id
        - tracker_id
        - shipment_id
        - type
        - value
        - unit
        - is_out_of_threshold
      additionalProperties: false
    last_metric:
      type: object
      nullable: true
      properties:
        id:
          type: string
          format: uuid
        measured_at:
          type: string
          minLength: 1
          format: date-time
...       
      required:
        - measured_at
        - battery
        - temperature
        - humidity
        - position
      additionalProperties: false
    user:
      type: object
      nullable: true
      properties:
        id:
          type: string
          minLength: 1
          format: uuid
....
```

<img width="953" alt="Screenshot 2024-03-22 at 10 10 07" src="https://github.com/asteasolutions/zod-to-openapi/assets/2225869/78e1594a-5533-46de-8458-877afaae7ace">
