### ISSUE TITLE
z.literal transform behaviour 

### ISSUE THREAD

**Issue by QuentinCln** [asteasolutions/zod-to-openapi#251]
I started using the package and I'm wondering why z.lieral resolve to openapi enum, it seems that it's the right behaviour from your tests [literal string](https://github.dev/asteasolutions/zod-to-openapi/blob/14c66843522b908535d791e3943b766868689a35/spec/types/string.spec.ts#L36-L37)

```typescript
        doc.content['application/json'].schema = z.object({
            message: z.literal(APPLICATION_ERRORS[errors[0] as keyof typeof APPLICATION_ERRORS].message), // string here
            code: z.literal(APPLICATION_ERRORS[errors[0] as keyof typeof APPLICATION_ERRORS].code),
            details: z.unknown().openapi({ description: 'detail of the error if needed' }),
        }).openapi(APPLICATION_ERRORS[errors[0] as keyof typeof APPLICATION_ERRORS]).strict()
```

resolve to: 

![image](https://github.com/user-attachments/assets/ee935f1f-2c91-42e0-9c54-3aeee62e46a4)

```yaml
    BAD_REQUEST:
      type: object
      properties:
        message:
          type: string
          enum:
            - invalid data
        code:
          type: string
          enum:
            - BAD_REQUEST
        details:
          nullable: true
          description: detail of the error if needed
      required:
        - message
        - code
```

i'm excepting a string when i declaring z.literal('foo') 

shouldn't [this](https://github.dev/asteasolutions/zod-to-openapi/blob/14c66843522b908535d791e3943b766868689a35/src/transformers/literal.ts#L10) use a switch on typeof zodSchema._def.value
