### ISSUE TITLE
Question. Why is z.custom not required by default

### ISSUE THREAD

**Issue by brupxxxlgroup** [asteasolutions/zod-to-openapi#252]
Following schema definition

```typescript
const dataSourceSchema = registry.register(
    "DataSource",
    z
      .object({
        urn: z.custom<string>().openapi({
          description: "A unique URN for this datasource.",
        }),
        uri: z.string().openapi({
          description: "A URI where this data originated from.",
        }),
        date: z.string().openapi({
          description: "A point in time when this datasource was processed.",
        }),
      })
      .openapi({
        description: "wsdsdsdsd",
      })
  );
```

will produce following yaml

```yaml

  DataSource:
    type: object
    properties:
      urn:
        nullable: true
        description: A unique URN for this datasource.
      uri:
        type: string
        description: A URI where this data originated from.
      date:
        type: string
        description: A point in time when this datasource was processed.
    required:
      - uri
      - date
    description: wsdsdsdsd
```

Why is it that

- nullable:true
- not required?

I have tried to work around with

```typescript
const dataSourceSchema = registry.register(
    "DataSource",
    z
      .object({
        urn: z.custom<string>().openapi({
          description: "A unique URN for this datasource.",
        }),
        uri: z.string().openapi({
          description: "A URI where this data originated from.",
        }),
        date: z.string().openapi({
          description: "A point in time when this datasource was processed.",
        }),
      })
      .openapi({
        description: "wsdsdsdsd",
        required : ["urn", "uri", "date"]
      })
  );
```

But when referencing this schema from another schema like this

```typescript
  const otherSchema = zodOpenApiController.getRegistry().register(
    "OtherSchema",
    z.object({
      datasource: dataSourceSchema,
    })
  );
```
the yaml seems not correct to me

```yaml
    DataSource:
      type: object
      properties:
        urn:
          nullable: true
          description: A unique URN for this datasource.
        uri:
          type: string
          description: A URI where this data originated from.
        date:
          type: string
          description: A point in time when this datasource was processed.
      required:
        - urn
        - uri
        - date
      description: wsdsdsdsd
    OtherSchema:
      type: object
      properties:
        datasource:
          allOf:
            - $ref: "#/components/schemas/DataSource"
            - required:
                - uri
                - date
```                 

What am i doing wrong? Why is it generating this strange **allOff**

Thx. for help!
