### ISSUE TITLE
[request]: Support for `x-tagGroups`

### ISSUE THREAD

**Issue by thiskevinwang** [asteasolutions/zod-to-openapi#74]
# Description

Hi 👋 ! Awesome project here. It would be nice to have `x-tagGroups` support or some recommendations for how to possibly extend `zod-to-openapi`

Seen at http://redocly.github.io/redoc
-> http://redocly.github.io/redoc/openapi.yaml

The spec yaml:
```yaml
x-tagGroups:
  - name: General
    tags:
      - pet
      - store
  - name: User Management
    tags:
      - user
  - name: Models
    tags:
      - pet_model
      - store_model
```

What it looks like in ReDoc UI:

![CleanShot 2022-12-03 at 11 29 08@2x](https://user-images.githubusercontent.com/26389321/205451216-3d134a90-4522-45a0-81dd-09a9784a1466.png)
