### ISSUE TITLE
Unexpected artifacts in components

### ISSUE THREAD

**Issue by elmeister** [asteasolutions/zod-to-openapi#77]
Hello

Consider the following code
```typescript
const errorComponent = openapi.registerComponent('schemas', 'error', {
  $ref: 'Error',
  type: 'object',
  properties: {
    code: {
      type: 'string',
    },
    message: {
      type: 'string',
    },
  },
});
// ...
responses[400] = {
  description: 'Error',
  content: {
    'application/json': {
      schema: errorComponent.ref,
    },
  },
};
```

Output for this case is
```yaml
"400":
  description: Error
  content:
    application/json:
      schema: *a1
```

Sometimes a bit different
```yaml
"400":
  description: Error
  content:
    application/json:
      schema:
        &a1
        $ref: "#/components/schemas/error"
```

What I'm doing wrong please?
